import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

const GREEN_HEADER = [198, 224, 180];
const GREEN_TOTAL  = [198, 224, 180];
const BLACK        = [0, 0, 0];
const WHITE        = [255, 255, 255];
const BORDER       = [180, 180, 180];

function buildTeamWeeklyPDF({ managerName, dateFrom, dateTo, rows }) {
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W   = pdf.internal.pageSize.width;

  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...BLACK);
  pdf.text("TEAM WEEKLY REPORTING", W / 2, 18, { align: "center" });

  pdf.setFontSize(9);
  pdf.setFont("helvetica", "bold");
  pdf.text("Manager :", 14, 26);
  pdf.setFont("helvetica", "normal");
  pdf.text(managerName || "", 38, 26);
  pdf.setFont("helvetica", "bold");
  pdf.text("Date From :", 105, 26);
  pdf.setFont("helvetica", "normal");
  pdf.text(dateFrom || "", 128, 26);
  pdf.setFont("helvetica", "bold");
  pdf.text("To :", 155, 26);
  pdf.setFont("helvetica", "normal");
  pdf.text(dateTo || "", 164, 26);



  const totals = { plan: 0, follow: 0, kit: 0, sp: 0, nac: 0 };
  const body = rows.map((r, i) => {
    totals.plan   += Number(r.plan)   || 0;
    totals.follow += Number(r.follow) || 0;
    totals.kit    += Number(r.kit)    || 0;
    totals.sp     += Number(r.sp)     || 0;
    totals.nac    += Number(r.nac)    || 0;
    return [
      i + 1,
      r.name || "",
      r.plan   || 0,
      r.follow || 0,
      r.kit    || 0,
      r.sp     || 0,
      r.nac    || 0,
    ];
  });

  body.push([
    { content: "TOTAL", colSpan: 2, styles: { fontStyle: "bold", fillColor: GREEN_TOTAL, halign: "left" } },
    { content: totals.plan,   styles: { fontStyle: "bold", fillColor: GREEN_TOTAL } },
    { content: totals.follow, styles: { fontStyle: "bold", fillColor: GREEN_TOTAL } },
    { content: totals.kit,    styles: { fontStyle: "bold", fillColor: GREEN_TOTAL } },
    { content: totals.sp,     styles: { fontStyle: "bold", fillColor: GREEN_TOTAL } },
    { content: totals.nac,    styles: { fontStyle: "bold", fillColor: GREEN_TOTAL } },
  ]);

  autoTable(pdf, {
    startY: 36,
    head: [["SR.NO", "NAME", "PLAN", "FOLLOW", "KIT", "SP", "NAC"]],
    body,
    styles: {
      fontSize: 9,
      cellPadding: { top: 2.5, right: 2.5, bottom: 2.5, left: 2.5 },
      halign: "center",
      valign: "middle",
      lineColor: BORDER,
      lineWidth: 0.3,
      textColor: BLACK,
    },
    headStyles: {
      fillColor: GREEN_HEADER,
      textColor: BLACK,
      fontStyle: "bold",
      fontSize: 9.5,
      halign: "center",
    },
    columnStyles: {
      0: { cellWidth: 16 },
      1: { cellWidth: 55, halign: "left" },
      2: { cellWidth: 20 },
      3: { cellWidth: 20 },
      4: { cellWidth: 20 },
      5: { cellWidth: 20 },
      6: { cellWidth: 20 },
    },
    alternateRowStyles: { fillColor: [255, 255, 255] },
  });

  // ── Watermark
  const H = pdf.internal.pageSize.height;
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "italic");
  pdf.setTextColor(150, 150, 150);
  pdf.text("Generated By MLMLIVE", W / 2, H - 5, { align: "center" });

  return pdf;
}

export function viewTeamWeeklyPDF(opts) {
  try {
    const pdf  = buildTeamWeeklyPDF(opts);
    const blob = pdf.output("blob");
    const url  = URL.createObjectURL(blob);
    const win  = window.open(url, "_blank");
    if (!win) window.location.href = url;
    setTimeout(() => URL.revokeObjectURL(url), 60000);
  } catch (e) {
    console.error("viewTeamWeeklyPDF error:", e);
    throw e;
  }
}

export function downloadTeamWeeklyPDF(opts) {
  try {
    const pdf      = buildTeamWeeklyPDF(opts);
    const filename = `Team-Weekly-Report-${opts.dateFrom || ""}-to-${opts.dateTo || ""}.pdf`;

    if (typeof window !== "undefined" && window.ReactNativeWebView) {
      const dataUri = pdf.output("datauristring");
      window.ReactNativeWebView.postMessage(JSON.stringify({
        type: "DOWNLOAD_PDF", base64: dataUri, fileName: filename,
      }));
      return;
    }

    const blob = pdf.output("blob");
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = filename;
    a.style.display = "none";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 10000);
  } catch (e) {
    console.error("downloadTeamWeeklyPDF error:", e);
    throw e;
  }
}
